### ISSUE TITLE
Add version to package.json

### ISSUE THREAD

**Issue by clusby** [alchemyplatform/modular-account#157]
Could we add a version field to package.json? This will allow downstream repos to import as an npm package (rather than forcing as a submodule only)

**Comment by adam-alchemy** [comment]
Thank you for your suggestion @clusby. We've added fields for `name` and `version` to the `package.json`.

To avoid writing over previous git tags, we've created the `v1.0.1-npm` tag to indicate that it is available as an NPM package. You should be able to install this using `pnpm install github:alchemyplatform/modular-account#v1.0.1-npm` (or switch out to your NPM package manager of choice).

Note that because this repo uses git submodules, you may have to manually configure dependency remappings if you import as an NPM package. As mentioned in #158 , we now make `BasePlugin` and other libraries and interfaces available via https://github.com/erc6900/modular-account-libs, which may be easier to use.
